services:
  melotts:
    build:
      context: .
      args:
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        no_proxy: ${no_proxy:-}
      dockerfile: Dockerfile-LNL
    image: melotts-server
    container_name: melotts
    restart: always
    ports:
      - "8000:8000"
    environment:
      - http_proxy=${http_proxy:-}
      - https_proxy=${https_proxy:-}
      - no_proxy=${no_proxy:-}
      - HF_HOME=/app/hf_home
      - NLTK_DATA=/app/nltk_data
      - TTS_LANGUAGE=auto # auto, EN, ES, FR, JP, KR, ZH, MS
    devices:
      - /dev/dri
    volumes:
      - ./.cache/tts/hf_home:/app/hf_home
      - ./.cache/tts/nltk_data:/app/nltk_data
      - ./.cache/tts/Malaya:/root/Malaya
      - ./.cache/tts/Malaya-Speech:/root/Malaya-Speech
      - ./.cache/tts/jieba:/tmp
    shm_size: 32G
    deploy:
      resources:
        limits:
          memory: 32G